[AdaHackBE-4#4] Adicionar arquivo de documentação do Swagger | Nova Funcionalidade | Documentação
adailtonasp/adahack-2024-backend pull request #51
Opened 2024-04-16 08:09 UTC by Sownatta

Arquivo de documentação do Swagger foi criado, documentando as rotas da aplicação.

2024-04-16 20:35 UTC, PatrickPSouza approved these changes

2024-04-16 22:04 UTC, FlightofIcarus requested changes
Retirar as rotas do tipo patch da documentação, uma vez que decidimos não mais a utilizar, optando por ficar, por enquanto, apenas com a put.

2024-04-17 01:51 UTC, Sownatta commented
As rotas do tipo patch foram retiradas da documentação.

2024-04-17 02:02 UTC, PatrickPSouza approved these changes

2024-04-17 08:38 UTC, closed without merging