Feat/database model
adailtonasp/adahack-2024-backend pull request #53
Opened 2024-04-16 19:13 UTC by adailtonasp

2024-04-16 19:35 UTC, Sownatta approved these changes

2024-04-16 22:06 UTC, FlightofIcarus requested changes
Pasta db é referente a infraestrutura, então deve ser movida para config como conversado no discord. Deve ser criada a pasta models na mesma hierarquia de controllers, onde os modelos de objeto interno da API serão salvos.

2024-04-17 01:02 UTC, adailtonasp commented
> Pasta db é referente a infraestrutura, então deve ser movida para config como conversado no discord. Deve ser criada a pasta models na mesma hierarquia de controllers, onde os modelos de objeto interno da API serão salvos.
Os locais da pasta foram corrigidos

2024-04-17 01:02 UTC, PatrickPSouza approved these changes

2024-04-17 01:22 UTC, FlightofIcarus approved these changes
As mudanças sugeridas foram corrigidas. Foi alterado o diretório da db, que saiu de src e foi para config, por ser infra. Aprovado!

2024-04-17 01:49 UTC, merged